from torch import nn
import torch

from architecture.pignn.deconv import DeConvNet
from architecture.pignn.mlp import MLP
from architecture.lstm.custom_unet import CustomUNet


class WindSpeedLSTM(nn.Module):
    """
    A U-Net based model that uses an LSTM at its bottleneck, designed for predicting wind speeds
    over a sequence of time steps. Wraps a `CustomUNet` with an LSTM-based center component.

    Attributes:
        unet (CustomUNet): The U-Net model with a center LSTM module.
    """

    def __init__(self, sequence_length):
        """
        Initializes the WindSpeedLSTM with a U-Net architecture and an LSTM bottleneck.

        Args:
            sequence_length (int): Length of the input sequence, which is also used for the output sequence.
        """
        super(WindSpeedLSTM, self).__init__()
        center_nn = WindSpeedLSTMHelper()  # LSTM-based helper for the U-Net's center
        self.unet = CustomUNet(sequence_length, sequence_length, center_nn)

    def forward(self, x):
        """
        Defines the forward pass through the U-Net with the LSTM bottleneck.

        Args:
            x (torch.Tensor): Input tensor of shape (batch_size, sequence_length, height, width).

        Returns:
            torch.Tensor: Output tensor of the same shape as input, with predicted values for wind speed.
        """
        x = self.unet(x)
        return x


class WindSpeedLSTMHelper(nn.Module):
    """
    Helper module that defines an LSTM-based center for the U-Net, processing features from the encoder
    and returning the transformed features to the decoder.

    Attributes:
        flatten (nn.Flatten): Layer to flatten input tensor for the LSTM.
        lstm (nn.LSTM): LSTM layer to process the flattened features.
    """

    def __init__(self):
        """
        Initializes the LSTM helper with a flattening layer and an LSTM module.
        """
        super(WindSpeedLSTMHelper, self).__init__()
        self.flatten = nn.Flatten(start_dim=2)
        self.lstm = nn.LSTM(64, 64)  # LSTM with input and hidden state sizes of 64

    def forward(self, x):
        """
        Defines the forward pass of the LSTM helper. Flattens the input, processes it with the LSTM,
        and reshapes the output to match U-Net decoding dimensions.

        Args:
            x (torch.Tensor): Input tensor of shape (batch_size, channels, height, width).

        Returns:
            torch.Tensor: Output tensor reshaped to (batch_size, channels, height, width) for U-Net compatibility.
        """
        x = self.flatten(x)
        x, _ = self.lstm(x)
        return x.reshape(-1, 1024, 8, 8)  # Reshapes output to match the U-Net decoder input


class WindSpeedLSTMDeConv(nn.Module):
    """
    An LSTM-based model with an MLP and Deconvolution layers for wind speed prediction.
    It processes sequence data, then uses an MLP and LSTM followed by a DeConvolution layer
    to generate spatially-structured outputs.

    Attributes:
        seq_length (int): Length of the input sequence.
        flatten (nn.Flatten): Layer to flatten input tensor for the LSTM.
        lstm (nn.LSTM): LSTM layer that processes the flattened features.
        mlp (MLP): Multi-Layer Perceptron for initial feature extraction.
        de_conv (DeConvNet): Deconvolutional network for structured output generation.
    """

    def __init__(self, seq_length, de_conv_dims, output_size):
        """
        Initializes the WindSpeedLSTMDeConv with an MLP, LSTM, and deconvolutional layers.

        Args:
            seq_length (int): Length of the input sequence.
            de_conv_dims (tuple): Dimensions for the DeConvNet.
            output_size (int): Size of the final output.
        """
        super(WindSpeedLSTMDeConv, self).__init__()
        self.seq_length = seq_length
        self.flatten = nn.Flatten(start_dim=2)
        self.lstm = nn.LSTM(64, 64, dtype=torch.float32)  # LSTM with float32 precision
        self.mlp = MLP(input_dim=500, output_dim=64, num_neurons=[128, 128, 64], hidden_act='ReLU')
        self.de_conv = DeConvNet(1, de_conv_dims, output_size=output_size)

    def forward(self, x):
        """
        Defines the forward pass of the model, which includes reshaping the input,
        processing it with the MLP and LSTM, and generating output with DeConvNet.

        Args:
            x (torch.Tensor): Input tensor reshaped to (batch_size, 1, 500).

        Returns:
            torch.Tensor: Output tensor with spatially-structured data generated by the DeConvNet.
        """
        x = self.mlp(x.reshape(-1, 1, 500))  # Process input with MLP
        x = self.flatten(x)
        x, _ = self.lstm(x)
        return self.de_conv(x.reshape(-1, 1, 8, 8))  # Reshape and pass through DeConvNet
